import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import CardRenderer from '../components/Cards/CardRenderer';

export const exportToHtml = async (data) => {
    // 1. Render the Grid content to static HTML
    // We wrap it in a simplified container similar to PreviewPanel
    // Normalize data: support array, data.items (from sample.json), or data.posts
    const items = Array.isArray(data) ? data : (data.items || data.posts || []);

    const contentHtml = renderToStaticMarkup(
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-8">
            {items.length > 0 ? (
                items.map((item, index) => (
                    <CardRenderer key={index} item={item} />
                ))
            ) : (
                <div className="text-white">No content found</div>
            )}
        </div>
    );

    // 2. Construct the full HTML document
    // We use Tailwind CDN for styling to ensure the exported file looks identical
    // We also inject some critical styles for dark mode background
    const timestamp = new Date().toLocaleDateString();

    const html = `<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JSON Export - ${timestamp}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    colors: {
                        background: {
                            primary: '#0f0f0f',
                            secondary: '#1a1a1a',
                            card: '#242424'
                        },
                        text: {
                            primary: '#ffffff',
                            secondary: '#a0a0a0'
                        },
                        accent: '#3b82f6'
                    }
                }
            }
        }
    </script>
    <style>
        body { background-color: #0f0f0f; color: #ffffff; font-family: sans-serif; }
        /* Custom scrollbar if needed */
    </style>
</head>
<body class="bg-background-primary min-h-screen">
    <header class="bg-background-secondary border-b border-white/5 p-4 sticky top-0 z-50">
        <div class="max-w-7xl mx-auto flex items-center justify-between">
            <h1 class="font-bold text-xl text-white">JSON Content Export</h1>
            <span class="text-sm text-text-secondary">${timestamp}</span>
        </div>
    </header>
    
    <main class="max-w-7xl mx-auto">
        ${contentHtml}
    </main>

    <footer class="text-center p-8 text-text-secondary text-sm">
        Generated by JSON Content Viewer
    </footer>
</body>
</html>`;

    // 3. Trigger Download
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `export-${Date.now()}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
